server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mayfill_dev?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root

  jpa:
    database: mysql
    hibernate:
      #   spring.jpa.hibernate.ddl-auto? ??
      #      update: ??? ???? ???? JPA? ?? ??? ??? ????.
      #      validate: ???? ???? ????? ???????? ????.
      #      create: ??? ???? ???? ???? ?? ????.
      #      create-drop: ???? ???? ??????? ??? ? ????.
      #      none: ??? ??? ?? ???.
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 50

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace