cloud:
  aws:
    credentials:
      accessKey: AKIAV5JSVJK3EWQXVEFP
      secretKey: 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
    s3:
      bucket: mayfillbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false