server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mayfill.cyy1hxjw52fe.ap-northeast-2.rds.amazonaws.com:3306/mayfill?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: mayfill_admin
    password: mayfill_password

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 50

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.amazonaws.util.EC2MetadataUtils: error