server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api
  address: 172.31.37.135

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mayfill_dev?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
    url: jdbc:mysql://mayfill.cyy1hxjw52fe.ap-northeast-2.rds.amazonaws.com:3306/mayfill?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: mayfill_admin
    password: mayfill_password

  jpa:
    database: mysql
    hibernate:
      #   spring.jpa.hibernate.ddl-auto? ??
      #      update: ??? ???? ???? JPA? ?? ??? ??? ????.
      #      validate: ???? ???? ????? ???????? ????.
      #      create: ??? ???? ???? ???? ?? ????.
      #      create-drop: ???? ???? ??????? ??? ? ????.
      #      none: ??? ??? ?? ???.
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 50

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace